use crate::app::SystemMetrics;
use crate::monitor::network::format_speed;

/// Formats a complete, readable system specs summary for sharing.
pub fn format_system_specs(m: &SystemMetrics) -> String {
    let cpu_cores_str = match (m.cpu_physical_cores, m.cpu_logical_cores) {
        (Some(p), l) if l > 0 => format!("{} Cores / {} Threads", p, l),
        (None, l) if l > 0 => format!("{} Threads", l),
        _ => String::new(),
    };

    let cpu_load_str = m.cpu_usage.map(|u| format!("{:.0}%", u)).unwrap_or_else(|| "N/A".to_string());
    let cpu_temp_str = m.cpu_temperature.map(|t| format!("{:.0}°C", t)).unwrap_or_else(|| "N/A".to_string());
    let cpu_freq_str = m.cpu_frequency.map(|f| format!("{:.2} GHz", f)).unwrap_or_default();

    let mut cpu_details = Vec::new();
    if !cpu_cores_str.is_empty() {
        cpu_details.push(cpu_cores_str);
    }
    if !cpu_freq_str.is_empty() {
        cpu_details.push(format!("Clock: {}", cpu_freq_str));
    }
    cpu_details.push(format!("Load: {} | Temp: {}", cpu_load_str, cpu_temp_str));

    // GPU
    let gpu_name = m.gpu_name.as_deref().unwrap_or("Generic Graphics");
    let gpu_load = m.gpu_usage.map(|u| format!("{:.0}%", u)).unwrap_or_else(|| "N/A".to_string());
    let gpu_temp = m.gpu_temperature.map(|t| format!("{:.0}°C", t)).unwrap_or_else(|| "N/A".to_string());
    let gpu_vram = match (m.gpu_memory_used, m.gpu_memory_total) {
        (Some(u), Some(t)) => format!("{:.1} / {:.1} GB", u as f64 / 1024.0 / 1024.0 / 1024.0, t as f64 / 1024.0 / 1024.0 / 1024.0),
        (None, Some(t)) => format!("{:.1} GB VRAM", t as f64 / 1024.0 / 1024.0 / 1024.0),
        _ => String::new(),
    };

    let ram_used = m.ram_used as f64 / 1024.0 / 1024.0 / 1024.0;
    let ram_total = m.ram_total as f64 / 1024.0 / 1024.0 / 1024.0;
    let disk_used = m.disk_used as f64 / 1024.0 / 1024.0 / 1024.0;
    let disk_total = m.disk_total as f64 / 1024.0 / 1024.0 / 1024.0;

    let mut s = String::new();
    s.push_str("=== VeroStat Hardware Specs ===\n");
    s.push_str(&format!("CPU: {}\n", m.cpu_name));
    s.push_str(&format!("     • {}\n", cpu_details.join(" • ")));

    s.push_str(&format!("GPU: {}\n", gpu_name));
    let mut gpu_details = Vec::new();
    if !gpu_vram.is_empty() {
        gpu_details.push(format!("VRAM: {}", gpu_vram));
    }
    gpu_details.push(format!("Load: {} | Temp: {}", gpu_load, gpu_temp));
    s.push_str(&format!("     • {}\n", gpu_details.join(" • ")));

    s.push_str(&format!("RAM: {:.1} / {:.1} GB ({:.0}%)\n", ram_used, ram_total, m.ram_usage));
    s.push_str(&format!("Storage: {:.0} / {:.0} GB ({:.0}%)\n", disk_used, disk_total, m.disk_usage));
    s.push_str(&format!("Network: ↓{} | ↑{}\n", format_speed(m.download_speed), format_speed(m.upload_speed)));
    s.push_str(&format!("Report generated by VeroStat v{}\n", env!("CARGO_PKG_VERSION")));

    s
}

/// Copies UTF-8 text to Windows Clipboard via native Win32 APIs.
pub fn copy_to_clipboard(text: &str) -> Result<(), String> {
    use windows::Win32::Foundation::HANDLE;
    use windows::Win32::System::DataExchange::{CloseClipboard, EmptyClipboard, OpenClipboard, SetClipboardData};
    use windows::Win32::System::Memory::{GlobalAlloc, GlobalLock, GlobalUnlock, GMEM_MOVEABLE};

    let wide: Vec<u16> = text.encode_utf16().chain(std::iter::once(0)).collect();
    let byte_count = wide.len() * std::mem::size_of::<u16>();

    unsafe {
        if OpenClipboard(None).is_err() {
            return Err("Failed to open Windows clipboard".to_string());
        }

        let _ = EmptyClipboard();

        let hmem = GlobalAlloc(GMEM_MOVEABLE, byte_count)
            .map_err(|e| format!("Failed to allocate global memory: {:?}", e))?;

        let ptr = GlobalLock(hmem);
        if ptr.is_null() {
            let _ = CloseClipboard();
            return Err("Failed to lock memory for clipboard".to_string());
        }

        std::ptr::copy_nonoverlapping(wide.as_ptr() as *const u8, ptr as *mut u8, byte_count);
        let _ = GlobalUnlock(hmem);

        // CF_UNICODETEXT = 13
        if SetClipboardData(13, HANDLE(hmem.0)).is_err() {
            let _ = CloseClipboard();
            return Err("Failed to set clipboard text".to_string());
        }

        let _ = CloseClipboard();
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_system_specs() {
        let mut m = SystemMetrics::default();
        m.cpu_name = "11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz".to_string();
        m.cpu_physical_cores = Some(6);
        m.cpu_logical_cores = 12;
        m.cpu_frequency = Some(2.7);
        m.cpu_usage = Some(18.0);
        m.cpu_temperature = Some(50.0);
        m.gpu_name = Some("NVIDIA GeForce RTX 3050 Laptop GPU".to_string());
        m.gpu_usage = Some(0.0);
        m.gpu_temperature = Some(51.0);
        m.ram_used = (14.6 * 1024.0 * 1024.0 * 1024.0) as u64;
        m.ram_total = (16.0 * 1024.0 * 1024.0 * 1024.0) as u64;
        m.ram_usage = 91.2;
        m.disk_used = 760 * 1024 * 1024 * 1024;
        m.disk_total = 1418 * 1024 * 1024 * 1024;
        m.disk_usage = 53.6;

        let output = format_system_specs(&m);
        assert!(output.contains("11th Gen Intel(R) Core(TM) i5-11400H"));
        assert!(output.contains("6 Cores / 12 Threads"));
        assert!(output.contains("NVIDIA GeForce RTX 3050"));
        assert!(output.contains("14.6 / 16.0 GB"));
        assert!(output.contains("760 / 1418 GB"));
    }
}
